/**********************************************************************
 * Extern for uportconnect
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var uportconnect = {
  "Connect": function () {},
  "ConnectCore": function () {},
  "Credentials": function () {},
  "MNID": {
    "decode": function () {},
    "encode": function () {},
    "isMNID": function () {}
  },
  "QRUtil": {
    "closeQr": function () {},
    "getQRDataURI": function () {},
    "openQr": function () {}
  },
  "SimpleSigner": function () {}
};
/**********************************************************************
 * End Generated Extern for uportconnect
/**********************************************************************/